#!/sbin/busybox sh

if [ "a$2" != "a" ]; then
        case "$2" in
                on)
                        echo 1 > $EXTERNAL_STORAGE/.fix_fs_on_boot_auto;
                ;;
                off)
                        rm -f $EXTERNAL_STORAGE/.fix_fs_on_boot_auto;
                ;;
        esac;
fi;

if [ -f $EXTERNAL_STORAGE/.fix_fs_on_boot_auto ]; then
        echo on;
else
        echo off;
fi;
